name: Rotate playlist (outer blob + key_b) and prune old files

on:
  schedule:
    # Every 2 days at 03:00 UTC
    - cron: "0 3 */2 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensures full history so commits push cleanly

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run rotation script
        run: node scripts/rotate_playlist.mjs
        env:
          PART_A: ${{ secrets.PART_A }}   # secret you already added in repo settings
          PART_B_LENGTH: "16"             # random key length, can change to 20–24
          FILE_PREFIX: "paidappsecure_"   # prefix for dated files
          OUTER_ALIAS: "latest.json"      # alias file used by Blogger
          KEYB_PATH: "key_b.txt"          # key file fetched by Blogger
          FALLBACK_OUTER: "paidappsecure_encoded_base64.json" # used on first run only

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "auto: rotate outer blob + key_b; prune >10d" || echo "No changes to commit"
          git push origin main
